### PR TITLE
( New Source ) LibreBook

### PR DESCRIPTION
**Pull request by OshekharO**

### CODE REVIEW

**Comment by ztimms73** [comment]
Lol, are you seriously opening a pull request with a source that only supports text and not images?

**Comment by OshekharO** [comment]
Oh ya sorry i forgot about that. Gone mad finding sources which have huge library

**Comment by OshekharO** [comment]
Oh ya sorry i forgot about that. Gone mad finding sources which have huge library

**Comment by nv95** [comment]
@OshekharO 
Do you at least check that it works before you create a pull request?

**Comment by OshekharO** [comment]
> @OshekharO Do you at least check that it works before you create a pull request?

Yes, i check all sources but i cannot check Russian sources as my ISP blocks it and I am not able to bypass it.

**Comment by OshekharO** [comment]
I have found many madara sources having more than 20k manga but i have not added them as they were showing some issues.

**Pull request closed without merging**
