### PR TITLE
Add: KomikManga & Fixes

### PR DESCRIPTION
**Pull request by OshekharO**
Arabic Site To Add: swatmanga.me (showing chapter not found and description not found)

### CODE REVIEW

**Comment by OshekharO** [comment]
Ready for merging.

**Comment by OshekharO** [comment]
Want me to add more sources? If not then it can be merged.

**Comment by OshekharO** [comment]
Want me to add more sources? If not then it can be merged.

**Comment by ztimms73** [comment]
> Want me to add more sources?

Sure, why not?

**Pull request merged**
