### PR TITLE
updates Arabic

### PR DESCRIPTION
**Pull request by OtakuArab**

### CODE REVIEW

**Comment by OtakuArab** [comment]
Why is the error repeated? I hope you can help

**Comment by NagaYZ** [comment]
You can check the details of why the build failed : e: [ksp] Manga source name must be uppercase: AZORAMoon

**Comment by OtakuArab** [comment]
> You can check the details of why the build failed : e: [ksp] Manga source name must be uppercase: AZORAMoon

Why source LikeManga Failed. Is there a problem with the codes? Can you help me? I am still a beginner in programming

**Comment by NagaYZ** [comment]
There is already a source called LIKEMANGA

**Comment by OtakuArab** [comment]
> There is already a source called LIKEMANGA

Thank you, brother, you helped me a lot

**Pull request merged**
