### PR TITLE
remove dead sources

### PR DESCRIPTION
**Pull request by dragonx943**
remove truyentranhlh, nettruyen, nettruyenmax and nhattruyen (completely closed, no further maintenance)

### CODE REVIEW

**Comment by Karutovn** [comment]
Pls keep nettruyen pls (some unofficial source can work with this

**Comment by davvarrr** [comment]
Since pr https://github.com/KotatsuApp/kotatsu-parsers/pull/537 we don't delete sources, but we add to it the @broken tag
in your request, the majority already have this tag.

**Comment by dragonx943** [comment]
> Pls keep nettruyen pls (some unofficial source can work with this

u can choose other sources instead such as blogtruyen, truyenqq, otakusan,...

**Comment by dragonx943** [comment]
> Since pr #537 we don't delete sources, but we add to it the @broken tag in your request, the majority already have this tag.

I do not support websites that have a poor history of development and have been involved in scandals on national television, even fake websites on the internet with a similar structure, so I hope u understand my opinion.

**Comment by Karutovn** [comment]
Hmm i think nhattruyen changed domain to nhattruyenvn.com

**Comment by dragonx943** [comment]
> Hmm i think nhattruyen changed domain to nhattruyenvn.com

fake website, for sure 100%

**Comment by dragonx943** [comment]
> new domain: "https://nhattruyenvn.com".

fake website with similar structure (so kotatsu still works)

**Comment by dragonx943** [comment]
> Since pr #537 we don't delete sources, but we add to it the @broken tag in your request, the majority already have this tag.

i will bring back NetTruyen and NhatTruyen, but u should not create too many source files for NetTruyen and NhatTruyen, just keep source in only one file and add many URLs to it like HentaiVN, and we can close and merge this pull request!

image

**Pull request closed without merging**
